name: simulator
description: "A (not just) device simulator for Flutter. Makes building multi-platform UIs a breeze"
version: 0.1.0
homepage: https://github.com/kekland/simulator

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  macos_window_utils: ^1.5.0
  url_launcher: ^6.2.4
  window_manager: ^0.3.8

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/skins/pixel_2/
    - assets/skins/pixel_2_xl/
    - assets/skins/pixel_3/
    - assets/skins/pixel_3_xl/
    - assets/skins/pixel_3a/
    - assets/skins/pixel_3a_xl/
    - assets/skins/pixel_4/
    - assets/skins/pixel_4_xl/
    - assets/skins/pixel_2/
    - assets/skins/pixel_4a/
    - assets/skins/pixel_5/
    - assets/skins/pixel_6/
    - assets/skins/pixel_6_pro/
    - assets/skins/pixel_6a/
    - assets/skins/pixel_7/
    - assets/skins/pixel_7_pro/
